server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowercaseServiceId: true
  jackson:
    default-property-inclusion: NON_NULL

#Eureka client
  eureka:
   client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # add public IP link here
      defaultZone: http://localhost:8761/eureka/
jwt:
  secret: secretkey
  token:
    validity: '18000'